# Generated by Django 5.1.6 on 2025-02-10 16:27

from django.db import migrations

def add_initial_records(apps, schema_editor):
    Record = apps.get_model('main_app', 'Record')
    Record.objects.create(name='In Rainbows', artist='Radiohead', genre='Alternative', release_date='2007-10-10')
    Record.objects.create(name='Chromakopia', artist='Tyler, The Creator', genre='Hip Hop', release_date='2023-06-23')

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_records),
    ]
