# Generated by Django 5.1.6 on 2025-02-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_add_initial_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
    ]
